### PR TITLE
Fix logten naming, fix order of arguments for atantwo.

### PR DESCRIPTION
**Pull request by ppebb**
atantwo had its arguments reversed, and its behavior differs from atan in that it accounts for atan being bounded between pi/2 and -pi/2, so further elaboration is necessary.

### CODE REVIEW

**Review by steviegt6 — APPROVED** [review]
LGTM

**Review by OliHeamon — APPROVED** [review]
LGTM! (Looks good to me)!

**Comment by ppebb** [comment]
LGTM! (Let's get this merged)!

**Comment by DylanDoe21** [comment]
Looks good to me!

**Comment by Smug-B** [comment]
LGTM! (Let's get this merged)! (See link for further details: https://tenor.com/view/jungkook-get-real-cat-photoshop-penis-gif-20979329)

**Comment by toasty599** [comment]
Thanks but I'm not interested in contributions to this.

**Pull request closed without merging**
